services:
  mongo:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - ./:/home/ubuntu
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge